QT += core gui widgets
TEMPLATE = app
CONFIG += console c++17


RESOURCES += \
    Images.qrc

HEADERS += \
    Graphics/Buildings/BuildingCharaterichtics.h \
    Controllers/Enums.h \
    Controllers/FindUnitWay.h \
    Controllers/FindVision.h \
    Controllers/Game.h \
    Controllers/IGame.h \
    Controllers/Player/BuildInTown.h \
    Controllers/Player/IMenuTownPlayer.h \
    Controllers/Player/IPlayer.h \
    Controllers/Player/ITownPlayer.h \
    Controllers/Player/Player.h \
    Controllers/Player/PlayerBuild.h \
    Controllers/Player/PlayerMap.h \
    Controllers/Player/PlayerRes.h \
    Controllers/Player/PlayerScience.h \
    Controllers/Player/PlayerTown.h \
    Controllers/Player/PlayerUnit.h \
    Controllers/Science.h \
    Controllers/TownBuildNeeds.h \
    Controllers/TownBuildings.h \
    Graphics/GraphicsController/GraphicsController.h \
    Graphics/GraphicsController/IMapGraphicsController.h \
    Graphics/GraphicsController/IMenuGraphicsController.h \
    Graphics/GraphicsController/IWindowGraphicsController.h \
    Graphics/GraphicsController/MapGraphicsController.h \
    Graphics/GraphicsController/MenuGraphicsController.h \
    Graphics/GraphicsController/WindowGraphicsController.h \
    Graphics/Menus/MenuInWindow/MenuLists.h \
    Graphics/Menus/MenuInWindow/OpenMenuLists.h \
    Graphics/Menus/MenuScience/MenuScience.h \
    Graphics/Menus/MenuScience/WidgetKnowledge.h \
    Graphics/Units/UnitsCharaterichtics.h \
    Graphics/Buildings/Building.h \
    Graphics/Buildings/Farm.h \
    Graphics/Buildings/FishingBoat.h \
    Graphics/Buildings/Fort.h \
    Graphics/Buildings/LumberMill.h \
    Graphics/Buildings/Mine.h \
    Graphics/Buildings/OilWell.h \
    Graphics/Buildings/Pasture.h \
    Graphics/Buildings/Quarry.h \
    Graphics/Buildings/Town.h \
    Graphics/Buildings/TradingPost.h \
    Graphics/Cell.h \
    Graphics/DrawWay.h \
    Graphics/Factories/FactoryBuild.h \
    Graphics/Factories/FactoryColor.h \
    Graphics/Factories/FactoryMenusUnit.h \
    Graphics/Factories/FactoryPixmap.h \
    Graphics/Factories/FactoryRes.h \
    Graphics/Factories/FactoryString.h \
    Graphics/Factories/FactoryUnits.h \
    Graphics/GameWindow.h \
    Graphics/GraphicsController/Calculations.h \
    Graphics/GraphicsController/CreateMap.h \
    Graphics/GraphicsController/EventsStructures.h \
    Graphics/GraphicsController/IGraphicsController.h \
    Graphics/GraphicsController/IPlayerGraphicsController.h \
    Graphics/GraphicsController/PlayerGraphicsController.h \
    Graphics/ICell.h \
    Graphics/IContent.h \
    Graphics/IDrawObject.h \
    Graphics/IMap.h \
    Graphics/InformationWidgets/StartMoveInform.h \
    Graphics/Map.h \
    Graphics/Menus/MenuTown/AWidgetTown.h \
    Graphics/Menus/MenuTown/IMenuTown.h \
    Graphics/Menus/MenuTown/InformWidget.h \
    Graphics/Menus/MenuTown/MenuAlreadyBuildTown.h \
    Graphics/Menus/MenuTown/MenuBuildTown.h \
    Graphics/Menus/MenuTown/MenuQueueTown.h \
    Graphics/Menus/MenuTown/MenuTown.h \
    Graphics/Menus/MenuTown/MenuTypeWorkTown.h \
    Graphics/Menus/MenuTown/WidgetTownBuilding.h \
    Graphics/Menus/MenuTown/WidgetTownUnit.h \
    Graphics/Menus/MenuInWindow/AMenuInWindow.h \
    Graphics/Menus/MenuInWindow/BottomMenu.h \
    Graphics/Menus/MenuInWindow/UpperMenu.h \
    Graphics/Menus/MenuUnit/AMenuForUnit.h \
    Graphics/Menus/MenuUnit/CitizenMenu.h \
    Graphics/Menus/MenuUnit/WarriorMenu.h \
    Graphics/Menus/MenuUnit/WorkerMenu.h \
    Graphics/Minimap.h \
    Graphics/Resources/Aluminum.h \
    Graphics/Resources/Coal.h \
    Graphics/Resources/Fish.h \
    Graphics/Resources/Gold.h \
    Graphics/Resources/Horses.h \
    Graphics/Resources/Iron.h \
    Graphics/Resources/Oil.h \
    Graphics/Resources/Res.h \
    Graphics/Resources/Silver.h \
    Graphics/Resources/Stone.h \
    Graphics/Resources/Uranium.h \
    Graphics/InformationWidgets/UnitInformation.h \
    Graphics/Units/Bowman.h \
    Graphics/Units/Citizen.h \
    Graphics/Units/Swordsman.h \
    Graphics/Units/Unit.h \
    Graphics/Units/Worker.h \
    IObject.h

SOURCES += \
    Controllers/FindUnitWay.cpp \
    Controllers/FindVision.cpp \
    Controllers/Game.cpp \
    Controllers/Player/BuildInTown.cpp \
    Controllers/Player/Player.cpp \
    Controllers/Player/PlayerMap.cpp \
    Controllers/Player/PlayerRes.cpp \
    Controllers/Player/PlayerScience.cpp \
    Controllers/Player/PlayerTown.cpp \
    Controllers/Science.cpp \
    Controllers/TownBuildNeeds.cpp \
    Graphics/Buildings/Building.cpp \
    Graphics/Buildings/Town.cpp \
    Graphics/Cell.cpp \
    Graphics/ControlContents.cpp \
    Graphics/DrawWay.cpp \
    Graphics/Factories/FactoryBuild.cpp \
    Graphics/Factories/FactoryColor.cpp \
    Graphics/Factories/FactoryMenusUnit.cpp \
    Graphics/Factories/FactoryPixmap.cpp \
    Graphics/Factories/FactoryRes.cpp \
    Graphics/Factories/FactoryString.cpp \
    Graphics/Factories/FactoryUnits.cpp \
    Graphics/GameWindow.cpp \
    Graphics/GraphicsController/Calculations.cpp \
    Graphics/GraphicsController/CreateMap.cpp \
    Graphics/GraphicsController/EventsStructures.cpp \
    Graphics/GraphicsController/GraphicsController.cpp \
    Graphics/GraphicsController/MapGraphicsController.cpp \
    Graphics/GraphicsController/MenuGraphicsController.cpp \
    Graphics/GraphicsController/PlayerGraphicsController.cpp \
    Graphics/GraphicsController/WindowGraphicsController.cpp \
    Graphics/InformationWidgets/StartMoveInform.cpp \
    Graphics/InformationWidgets/UnitInformation.cpp \
    Graphics/Map.cpp \
    Graphics/Menus/MenuInWindow/MenuLists.cpp \
    Graphics/Menus/MenuInWindow/OpenMenuLists.cpp \
    Graphics/Menus/MenuScience/MenuScience.cpp \
    Graphics/Menus/MenuScience/WidgetKnowledge.cpp \
    Graphics/Menus/MenuTown/AWidgetTown.cpp \
    Graphics/Menus/MenuTown/InformWidget.cpp \
    Graphics/Menus/MenuTown/MenuAlreadyBuildTown.cpp \
    Graphics/Menus/MenuTown/MenuBuildTown.cpp \
    Graphics/Menus/MenuTown/MenuQueueTown.cpp \
    Graphics/Menus/MenuTown/MenuTown.cpp \
    Graphics/Menus/MenuTown/MenuTypeWorkTown.cpp \
    Graphics/Menus/MenuTown/WidgetTownBuilding.cpp \
    Graphics/Menus/MenuTown/WidgetTownUnit.cpp \
    Graphics/Menus/MenuUnit/AMenuForUnit.cpp \
    Graphics/Menus/MenuInWindow/AMenuInWindow.cpp \
    Graphics/Menus/MenuInWindow/BottomMenu.cpp \
    Graphics/Menus/MenuUnit/CitizenMenu.cpp \
    Graphics/Menus/MenuInWindow/UpperMenu.cpp \
    Graphics/Menus/MenuUnit/WarriorMenu.cpp \
    Graphics/Menus/MenuUnit/WorkerMenu.cpp \
    Graphics/Minimap.cpp \
    Graphics/Resources/Res.cpp \
    Graphics/Units/Unit.cpp \
    Graphics/Units/Worker.cpp \
    main.cpp

